apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeDeploymentCoordinator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kubeDeploymentCoordinator.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeDeploymentCoordinator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubeDeploymentCoordinator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeDeploymentCoordinator.serviceAccountName" . }}
      restartPolicy: Always
      enableServiceLinks: false
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /kube-deployment-coordinator
          {{- with .Values.extraArgs }}
          - {{ . | quote }}
          {{- end }}

          {{- if .Values.leaderElection.enabled }}
          - --leader-elect=true
          - --leader-election-id={{ .Values.leaderElection.id | default "kube-deployment-coordinator.containerinfra.nl" }}
          {{- end }}
    
          ports:
            - name: metrics
              containerPort: 7712
            - name: health
              containerPort: 7713
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: 9443
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: tempdir
              mountPath: /tmp
            {{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 12 }}
      readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 12 }}
        
      volumes:
        - name: tempdir
          emptyDir: {}
        {{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
        - name: cert
          secret:
            secretName: {{ .Values.webhook.certManager.secretName | default "webhook-server-cert" }}
            defaultMode: 420
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

