apiVersion: v2
name: kube-deployment-coordinator
description: Helm chart for deploying the Kube Secrets Operator
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - 'https://github.com/containerinfra/kube-deployment-coordinator'
