# permissions for end users to edit deploymentcoordinations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-deployment-coordinator
    app.kubernetes.io/managed-by: kustomize
  name: deploymentcoordination-editor-role
rules:
- apiGroups:
  - apps.containerinfra.nl
  resources:
  - deploymentcoordinations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.containerinfra.nl
  resources:
  - deploymentcoordinations/status
  verbs:
  - get
